"""Create draft PRs on GitHub forks for chaos scenario changes."""

from __future__ import annotations

import logging
import os
import subprocess
from pathlib import Path
from urllib.parse import urlparse

from dotenv import load_dotenv

from src.apis.github_client import GitHubClient
from src.models import GapAnalysis

load_dotenv()

logger = logging.getLogger(__name__)

_krkn_repo_url = os.environ.get("KRKN_REPO_URL", "https://github.com/krkn-chaos/krkn")
_url_parts = urlparse(_krkn_repo_url).path.strip("/").split("/")
UPSTREAM_OWNER = _url_parts[0] if len(_url_parts) >= 1 else "krkn-chaos"
_UPSTREAM_REPO = _url_parts[1] if len(_url_parts) >= 2 else "krkn"

# Local fork paths
FORK_PATHS = {
    "krkn": Path(os.environ.get("KRKN_REPO_PATH", str(Path.home() / "krkn"))),
    "krkn-hub": Path.home() / "krkn-hub",
    "website": Path.home() / "website",
    "release": Path.home() / "release",
}

FORK_OWNER = os.environ.get("GITHUB_FORK_OWNER", "shahsahil264")


def _run_git(repo_path: Path, *args: str) -> tuple[int, str]:
    """Run a git command in a repo directory."""
    cmd = ["git", "-C", str(repo_path)] + list(args)
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    return result.returncode, result.stdout.strip() + result.stderr.strip()


def _create_branch(repo_path: Path, branch_name: str) -> bool:
    """Create a new branch from upstream main."""
    # Fetch upstream
    code, out = _run_git(repo_path, "fetch", "upstream", "main")
    if code != 0:
        logger.error("Failed to fetch upstream: %s", out)
        return False

    # Create branch from upstream/main
    code, out = _run_git(repo_path, "checkout", "-b", branch_name, "upstream/main")
    if code != 0:
        # Branch might already exist
        code, out = _run_git(repo_path, "checkout", branch_name)
        if code != 0:
            logger.error("Failed to create/checkout branch %s: %s", branch_name, out)
            return False

    return True


def _write_file(repo_path: Path, file_path: str, content: str) -> bool:
    """Write a file in the repo."""
    full_path = repo_path / file_path
    full_path.parent.mkdir(parents=True, exist_ok=True)
    full_path.write_text(content)
    return True


def _commit_and_push(repo_path: Path, branch_name: str, message: str, files: list[str]) -> bool:
    """Stage files, commit, and push to origin."""
    for f in files:
        _run_git(repo_path, "add", f)

    code, out = _run_git(repo_path, "commit", "-m", message)
    if code != 0:
        logger.error("Failed to commit: %s", out)
        return False

    code, out = _run_git(repo_path, "push", "-u", "origin", branch_name)
    if code != 0:
        logger.error("Failed to push: %s", out)
        return False

    return True


def _cleanup_branch(repo_path: Path) -> None:
    """Switch back to main branch."""
    _run_git(repo_path, "checkout", "main")


def create_scenario_pr(
    github: GitHubClient,
    gap: GapAnalysis,
    scenario_yaml: str,
    scenario_filename: str,
    dry_run: bool = True,
) -> dict | None:
    """Create a PR on krkn-chaos/krkn with a new/modified scenario YAML.

    Args:
        github: GitHub client
        gap: The gap analysis that triggered this PR
        scenario_yaml: The YAML content for the scenario
        scenario_filename: Filename under scenarios/openshift/ (e.g., etcd_throttling.yaml)
        dry_run: If True, show what would be done without creating

    Returns:
        PR dict or None
    """
    repo_path = FORK_PATHS["krkn"]
    branch_name = f"chaos-coordinator/{gap.bug.key.lower()}"
    scenario_path = f"scenarios/openshift/{scenario_filename}"

    if dry_run:
        logger.info("DRY RUN — would create PR:")
        logger.info("  Repo: %s/%s -> %s/%s", FORK_OWNER, "krkn", UPSTREAM_OWNER, "krkn")
        logger.info("  Branch: %s", branch_name)
        logger.info("  File: %s", scenario_path)
        return {"dry_run": True, "branch": branch_name, "file": scenario_path}

    if not repo_path.exists():
        logger.error("krkn repo not found at %s", repo_path)
        return None

    # Create branch
    if not _create_branch(repo_path, branch_name):
        return None

    try:
        # Write scenario file
        _write_file(repo_path, scenario_path, scenario_yaml)

        # Commit and push
        commit_msg = (
            f"feat: add chaos scenario for {gap.bug.key}\n\n"
            f"Bug: {gap.bug.url}\n"
            f"Failure mode: {gap.bug.summary}\n"
            f"Generated by krkn-chaos-coordinator"
        )
        if not _commit_and_push(repo_path, branch_name, commit_msg, [scenario_path]):
            return None

        # Create PR via GitHub API
        pr_title = f"[chaos-coordinator] {gap.bug.key}: Add chaos scenario"
        pr_body = (
            f"## Auto-generated Chaos Scenario\n\n"
            f"**Bug:** [{gap.bug.key}]({gap.bug.url})\n"
            f"**Component:** {gap.bug.component}\n"
            f"**Failure Mode:** {gap.bug.summary}\n\n"
            f"### Changes\n\n"
            f"- Added `{scenario_path}`\n\n"
            f"### Confidence\n\n"
            f"{gap.reasoning}\n\n"
            f"---\n"
            f"*Generated by krkn-chaos-coordinator*"
        )

        url = f"https://api.github.com/repos/{UPSTREAM_OWNER}/{_UPSTREAM_REPO}/pulls"
        payload = {
            "title": pr_title,
            "body": pr_body,
            "head": f"{FORK_OWNER}:{branch_name}",
            "base": "main",
            "draft": True,
        }

        try:
            response = github._session.post(url, json=payload, timeout=30)
            response.raise_for_status()
            pr = response.json()
            logger.info("Created PR: %s", pr.get("html_url"))
            return pr
        except Exception as e:
            logger.error("Failed to create PR: %s", e)
            return None

    finally:
        _cleanup_branch(repo_path)


def generate_scenario_yaml(gap: GapAnalysis) -> tuple[str, str]:
    """Generate a scenario YAML file content based on the gap analysis.

    Returns (yaml_content, filename).
    """
    bug = gap.bug
    component = bug.component.lower().replace(" ", "_").replace("/", "_")
    bug_id = bug.key.lower().replace("-", "_")
    filename = f"{component}_{bug_id}.yaml"

    # Determine scenario type based on injection method
    from src.agents.act import _infer_injection_method
    _, plugin, _ = _infer_injection_method(gap)

    # Map plugin to scenario type
    plugin_to_type = {
        "hogs (hog_scenarios)": "hog_scenarios",
        "node_actions (node_scenarios)": "node_scenarios",
        "pod_disruption (pod_disruption_scenarios)": "pod_disruption_scenarios",
        "network_chaos (network_chaos_scenarios)": "network_chaos_scenarios",
        "network_chaos (network_chaos_ng_scenarios)": "network_chaos_ng_scenarios",
        "time_actions (time_scenarios)": "time_scenarios",
    }
    scenario_type = plugin_to_type.get(plugin, "pod_disruption_scenarios")

    # Generate YAML based on scenario type
    if scenario_type == "hog_scenarios":
        yaml_content = f"""# Chaos scenario for {bug.key}: {bug.summary}
# Generated by krkn-chaos-coordinator
# Bug: {bug.url}
#
# This scenario creates resource pressure to test component resilience
# under load. Modify the targets and thresholds as needed.

- config:
    scenario_type: hog_scenarios
    node_selector:
      node-role.kubernetes.io/master: ""
    cpu:
      target: 80
      duration: 300
    memory:
      target: 80
      duration: 300
"""
    elif scenario_type == "node_scenarios":
        yaml_content = f"""# Chaos scenario for {bug.key}: {bug.summary}
# Generated by krkn-chaos-coordinator
# Bug: {bug.url}
#
# This scenario tests node failure and recovery behavior.

node_scenarios:
  - actions:
    - node_stop_start_scenario
    label_selector: node-role.kubernetes.io/master
    instance_count: 1
    runs: 1
    timeout: 600
    duration: 60
    cloud_type: aws
    kube_check: true
    poll_interval: 15
"""
    elif scenario_type == "network_chaos_scenarios":
        yaml_content = f"""# Chaos scenario for {bug.key}: {bug.summary}
# Generated by krkn-chaos-coordinator
# Bug: {bug.url}
#
# This scenario injects network disruption to test resilience.

network_chaos:
  duration: 300
  ingress:
    latency: 200ms
    loss: 0.05
  egress:
    latency: 200ms
    loss: 0.05
  execution_type: parallel
  node_selector:
    node-role.kubernetes.io/master: ""
  wait_duration: 300
  target_pod_labels:
    app: {component}
"""
    else:
        # Default: pod disruption
        namespace = "openshift-etcd" if "etcd" in component else f"openshift-{component}"
        yaml_content = f"""# Chaos scenario for {bug.key}: {bug.summary}
# Generated by krkn-chaos-coordinator
# Bug: {bug.url}
#
# This scenario disrupts pods to test component resilience and recovery.

- id: {bug_id}
  config:
    namespace_pattern: ^{namespace}$
    label_selector: ''
    kill: 1
    krkn_pod_recovery_time: 120
    expected_pod_count: 3
    runs: 1
"""

    return yaml_content, filename
